### ISSUE TITLE
chapter table misaligned in Twenty Fifteen

### ISSUE THREAD

**Issue by katrinleinweber** [podlove/podlove-web-player#215]
I know you said several times that theme problems should be taken to the theme developers, but since this is the [new default theme](https://make.wordpress.org/core/2014/09/09/twenty-fifteen/) in [WP4.1](https://wordpress.org/news/2014/11/wordpress-4-1-beta-1/)... ;-) It causes overly wide "Start time"- and "Duration"-[columns](https://github.com/podlove/podlove-web-player/blob/c70927ba2694243930157aa3687090116e2e502c/src/js/modules/chapter.js#L14), at the cost of  the chapter titles. Apparently independent of screen width, because it looks almost the same on a 1920px wide monitor (screenshot) and at 1024px.

![podlove-webplayer-twenty-fifteen-table-misaligned](https://cloud.githubusercontent.com/assets/9948149/5501910/6e2dfe0e-8762-11e4-9eea-af20f6ce7d0e.jpg)

**Comment by katrinleinweber** [comment]
Hier noch ein paar reale Beispiele:
http://www.physikalischesoiree.at/archives/2967
http://www.bienenpodcast.at/bg008-imkereiausbildung/
http://www.lobundtadel.eu/lut028/

**Comment by plutonik-a** [comment]
Hi Katrin,

The bug is caused by the WP theme 'twentyfifteen' 

    /wp-content/themes/twentyfifteen/style.css?ver=4.1

lines 397 - 411

    table,
    th,
    td {
	    border: 1px solid #eaeaea;
	    border: 1px solid rgba(51, 51, 51, 0.1);
    }

    table {
	    ...
	    table-layout: fixed; /* Prevents HTML tables from becoming too wide */
	    ...
    }

These styles need to be overridden, as they cause fixed columns in tables with highlighted borders.
For those who are running out of patience for that bug to be fixed, I recommend to copy&paste following lines as a quick fix:

    table,
    th,
    td {
	    border: none;
    }

    table {	
	    table-layout: auto;	
    }

We are still busy on releasing our next player version, but hoping to fix that bug quite soon as a proper solution for all users.
