### ISSUE TITLE
Support for Live Streams

### ISSUE THREAD

**Issue by cato-** [podlove/podlove-web-player#223]
It would be nice to use the player also for playing live streams (e.g. on xenim.de). Necessary for this seem to be the following features, ordered by importance:
- Select best fitting format and bitrate from supplied URLs (MP3, OPUS, HLS)
- Minimal UI: Just a play/stop button, button for popup with direct URLs, maybe elapsed time
- Popup which shows supplied URLs for usage in external players
- Possibility to start with an empty player and add URLs later with API calls. Usefull for having a waiting Site, which starts playing when streams gets available.

**Comment by ChrisDoerr** [comment]
Since there is no proper end time when streaming, the typical "NaN:NaN:NaN" is being displayed instead.

Would it be possible to catch that and, for example, add a "hidden" class to the DOM element? Then you could/should hide the NaN text in the CSS like

    .mejs-duration.hidden { visibility: hidden; }
![podlove-player-stream-nan](https://cloud.githubusercontent.com/assets/1961501/8092469/2b4d21f6-0fba-11e5-9ecf-533332493683.png)

**Comment by PhilipBanse** [comment]
Hi,

is it possible to use podlove webplayer for livestreams? how? 

thanks,

Philip
